Hyperion/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('HyperionApp.urls')),
]

HyperionApp/urls.py
from django.urls import path
from . import views

app_name = "HyperionApp"

urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.signin, name='login'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('signout/', views.signout, name='signout'),
]

HyperionApp/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

# Create your models here.
class User(AbstractUser):
    title = models.CharField(max_length=150)
    first_name = models.CharField(max_length=150)
    last_name = models.CharField(max_length=100)
    dob = models.CharField(max_length=12)
    email = models.CharField(max_length=254, unique=True)
    password = models.CharField(max_length=50)
    credit_score = models.IntegerField(max_length=3)

    REQUIRED_FIELDS=[]
    # This forces Django to use the email as the username. The username is
    # used as part of the authentication checks performed by
    # `authenticate()` function
    USERNAME_FIELD='email'

HyperionApp/forms.py
from django import forms
from .models import User
from django.contrib.auth.hashers import make_password, check_password

class signup_form(forms.Form):
    title = forms.CharField(max_length=150)
    first_name = forms.CharField(label='Last name(s)', max_length=150)
    last_name = forms.CharField(label='First Name', max_length=100)
    dob_day = forms.CharField(label='Dob_day', max_length=2)
    dob_month = forms.CharField(label='Dob_month', max_length=2)
    dob_year = forms.CharField(label='Dob_year', max_length=4)
    email = forms.EmailField(label='Email', max_length=254)
    password = forms.CharField(max_length=254)
    confirm_password = forms.CharField(max_length=254)

    # Verify if there already is an account that uses the same email;
    def clean_email(self):
        cleaned_data = super().clean()
        email = cleaned_data.get("email")

        user = User.objects.all().filter(email=email)

        if len(user) > 0:
            raise forms.ValidationError("There already is an account that uses this email")
        else:
            return email

    # Verify if the password and confirm password fields match;
    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")

        if password != confirm_password:
            raise forms.ValidationError("Passwords do not match")
        else:
            return cleaned_data

        # The 'def clean_password' method does cleaning specific to that
        # particular attribute.
        # The 'def clean()' method performs validation that requires access
        # to multiple form fields.
        # Here you must use `def clean(self)` and not `def clean_password`.
        # This is because the order of 'cleaning' matters.
        # If you use `def clean_password`, django will only clean the
        # 'password' input BUT you need the 'confirm_password' as well which
        # not yet cleaned.

class login_form(forms.Form):
    email = forms.EmailField(label='Email', max_length=254)
    password = forms.CharField(max_length=254)

    # Verify that the email exists in the database;
    # def clean_email(self):
    #     cleaned_data = super().clean()
    #     email = cleaned_data.get("email")
    #
    #     user = User.objects.all().filter(email=email)
    #
    #     if len(user) == 0:
    #         raise forms.ValidationError("Username and password do not match our records")
    #     else:
    #         return email
    #
    # # Verify if the password matches the one in the db;
    # def clean_password(self):
    #     cleaned_data = super().clean()
    #     email = cleaned_data.get("email")
    #     password = cleaned_data.get("password")
    #
    #     user = User.objects.all().filter(email=email)
    #
    #     if not check_password(password, user[0].password):
    #         raise forms.ValidationError("Username and password do not match our records")
    #     else:
    #         return password

HyperionApp/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import signup_form
from .forms import login_form
from django import forms
from .models import User
from django.contrib.auth.hashers import make_password, check_password
from django.contrib.auth import authenticate, login, logout
import random

# Create your views here.
def index(request):
    return render(request, 'index.html')

def signup(request):

    if request.user.is_authenticated:
        return redirect('HyperionApp:dashboard')

    if request.method == 'GET':
        return render(request, 'signup.html')

    elif request.method == 'POST':

        signup_instance = signup_form(request.POST)

        if not signup_instance.is_valid():
            return render(request, 'signup.html', context={ 'form': signup_instance })

        else:
            # Prepare user's inputs to be sent to the db
            title = signup_instance.cleaned_data['title']
            first_name = signup_instance.cleaned_data['first_name']
            last_name = signup_instance.cleaned_data['last_name']

            dob_concatenated = signup_instance.cleaned_data['dob_day'] + "/" + signup_instance.cleaned_data['dob_month'] + "/" + signup_instance.cleaned_data['dob_year']

            email = signup_instance.cleaned_data['email']
            password = signup_instance.cleaned_data['password']

            encrypted_password = make_password(password)

            # Generate random credit score
            credit_score = random.randint(300, 999)

            # Send credit score and inputs to db
            add_db = User(title=title, first_name=first_name, last_name=last_name, dob=dob_concatenated, email=email, password=encrypted_password, credit_score=credit_score)
            add_db.save()

            return redirect('HyperionApp:login')


def signin(request):

    if request.user.is_authenticated:
        return redirect('HyperionApp:dashboard')

    if request.method=='GET':
        return render(request, 'login.html')

    elif request.method=='POST':
        # Create an instance of your login_form
        login_instance = login_form(request.POST)

        # Input validation (it triggers the conditions written in forms.py)
        if not login_instance.is_valid():
            return render(request, 'login.html', context={'errors': login_instance.errors.values()})

        # Django forces you to use `is_valid` before cleaning data. There is no
        # `cleaned_data` before `is_valid`
        username = login_instance.cleaned_data['email']
        password = login_instance.cleaned_data['password']

        # Authentication checks. Django provides this by default (checks if
        # username exists, if password is correct)
        user = authenticate(request, username=username, password=password)

        # Handle authentication error
        if user is None:
            errors = ['Username and password do not match our records']
            return render(request, 'login.html', context={'errors': errors })

        # Create session
        login(request, user)

        return redirect('HyperionApp:dashboard')

def dashboard(request):
    # Limit access to dashboard if users are not logged-in
    if request.user.is_authenticated:
        return render(request, 'dashboard.html')

    else:
        return redirect('HyperionApp:login')

def signout(request):
    logout(request)
    return redirect('HyperionApp:index')

HyperionApp/templates/base1.html
{% load static %}

<!DOCTYPE html>
  <html lang="en" dir="ltr">

  <head>
    <meta charset="utf-8">
    <title></title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;1,400&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/0c3bf41138.js" crossorigin="anonymous"></script>
  </head>

  <body>

  <!-- Navbar -->
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
        <a href="{% url 'HyperionApp:index' %}" class="navbar-brand" href="#">Hidden brand</a>

        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Credit score & report</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="#">Compare credit offers</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="#">Insurance</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="#" tabindex="-1" aria-disabled="true">Help & assistance</a>
          </li>
        </ul>

        <div class="d-flex">
          <a class="nav-link d-flex search" href="#">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
              <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
            </svg>
          </a>

          {% if user.is_authenticated %}
            <a href="{% url 'HyperionApp:signout' %}" class="nav-link active nav-item" href="#">Log out</a>

            {% else %}
            <a href="{% url 'HyperionApp:login' %}" class="nav-link active nav-item" href="#">Sign in</a>
            <a href="{% url 'HyperionApp:signup' %}" class="btn btn-outline-success login-btn">Sign up</a>
          {% endif %}

        </div>
      </div>
    </div>
  </nav>

  {% block content %}

  {% endblock %}

  <!-- Footer -->
  <section>
    <div class="footer-section">
      <div class="container">
        <div class="row footer">

          <div class="col-3">
            <h6 class="col-title">About Hyperion</h6>
              <a href="#"><p>Why Hyperion?</p></a>
              <a href="#"><p>FAQs</p></a>
              <a href="#"><p>Affiliate</p></a>
              <a href="#"><p>Careers</p></a>
            </div>

            <div class="col-3">
              <h6 class="col-title">Resources</h6>
              <a href="#"><p>Press</p></a>
              <a href="#"><p>Modern Slavery</p></a>
              <a href="#"><p>Investor Relations</p></a>
              <a href="#"><p>Social Action</p></a>
            </div>

            <div class="col-3 legal">
              <h6 class="col-title">Legal</h6>
              <a href="#"><p>Terms & Conditions</p></a>
              <a href="#"><p>Cookies & online marketing</p></a>
              <a href="#"><a href="#"><p>Data Privacy</p></a>
              <a href="#"><p>Marketing claims</p></a>
            </div>

            <div class="col-3 social-media">
              <h6 class="col-title">Where to find us</h6>
              <div class="contact">
                <a href="#">Contact@hyperion.com</a>
                <div class="social-media">
                  <a href="#"><i class="fab fa-twitter-square"></i></a>
                  <a href="#"><i class="fab fa-facebook-square"></i></a>
                </div>
              </div>

              <div class="apps">
                <h6>Download our app</h6>
                <a href="#"><img alt="Go to the Google Play Store" src="https://intlck.imgix.net/0.105.0/illustrations/download_google_play.svg?auto=compress%2Cformat" width="110"></a>
                <a href="#"><img alt="Go to the Apple App Store" src="https://intlck.imgix.net/0.105.0/illustrations/download_app_store.svg?auto=compress%2Cformat" width="110"></a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </body>
  </html>

HyperionApp/templates/dashboard.html
{% extends 'base1.html' %}

{% block content %}

<!-- Dashboard -->
<section class="dashboard-section">
  <div class="container">
    <div class="col-12 dashboard">

      <div class="hello">
        <h2>Hello, <a href="">{{ user }}</a>!

          {% if user.credit_score < 500 %}
            Keep going, your score is {{ user.credit_score }}.

          {% elif user.credit_score >= 500 and user.credit_score <= 800 %}
            You're doing good, your score is {{ user.credit_score }}.

          {% elif user.credit_score > 800 %}
            You're doing excellent, your score is {{ user.credit_score }}.

          {% endif %}

        </h2>

        <p class="credit-item">Your score means you're all set for competitive credit cards, loans and mortgages.</p>
      </div>

      <div class="two-columns">

        <div class="col-4 diagram-section">
          <img src="/static/creditmeter2.jpg" height="430px">
            <div class="score-text">
              Your credit score is: <span>899</span>
              out of 999
            </div>
        </div>

        <div class="col-8 credit-explained">
          <div class="first-section">
            <h3>About your credit</h3>
            <p>This is the most recent information as supplied and used by lenders. Note that it could be up to four to six weeks old. Don't recognise this information? Find out <a href="#" class="info">here</a> what you can do. </p>

            <div class="two-containers">

              <div class="col-6 borrowing">
                <p class="title">Your total borrowing</p>
                <p>Our records do not show any active credit accounts registered under your name.</p>
              </div>

              <div class="col-6 offers-section">
                <div class="offers-item credit-row">
                  <span><i class="far fa-credit-card"></i>Credit cards (0)</span>
                  <a class="btn btn-outline-success login-btn small-btn">Details</a>
                </div>

                <div class="offers-item loans-row">
                  <span><i class="fas fa-coins"></i>Loans (0)</span>
                  <a class="btn btn-outline-success login-btn small-btn">Details</a>
                </div>

                <div class="offers-item mortages-row">
                  <span><i class="fas fa-home"></i>Mortgages (0)</span>
                  <a class="btn btn-outline-success login-btn small-btn">Details</a>
                </div>
              </div>
            </div>
          </div>

          <div class="upgrade">
            <p>Compare your credit score with other agencies and much more when ypu upgrade to HyperExpert.</p>
            <a class="btn btn-outline-success login-btn">Start today</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}

HyperionApp/templates/index.html
{% extends 'base1.html' %}

{% block content %}

<!-- Hero -->
<section class="hero-section">
  <div class="hero">
  <div class="container">

    <div class="hero-text">
      <h1>Get your FREE<br>Experian Credit Score</h1>
      <h3>And see if you can instantly boost it.</h3>
      <a class="btn btn-outline-success login-btn">Sign up free!</a>
    </div>

    <div class="hero-image">
      <img src="/static/hero1.png">
    </div>
  </div>
</div>
</section>

<!-- Why us section -->
<section class="why-us container">

  <h2>We’ve got the score that counts</h2>

  <div class="row align-items-start">

    <div class="col why-item">
      <i class="fas fa-rocket"></i>
      <h3>Instantly boost your credit score</h3>
      <h4>Simply connect your current account and boost it using our free feature.</h4>
    </div>

    <div class="col why-item">
      <i class="fas fa-star"></i>
      <h3>The UK's most trusted credit score app</h3>
      <h4>Join over 10 million happy humans who use Experian Credit Score.</h4>
    </div>

    <div class="col why-item">
      <i class="fas fa-money-bill-wave"></i>
      <h3>It's free forever, including score boost</h3>
      <h4>We will never charge you for checking or boosting your score. It's a promise!</h4>
    </div>
  </div>
</section>

<!-- Apply for credit -->
<section class="credit-section">

      <div class="container">
        <div class="row">

        <div class="col-7 credit-item">
          <div>
            <h3>Know your chances of acceptance before you apply for a loan.</h3>
            <h4>We’ve got the data that matters. We use it to benefit you best by finding credit cards and personal loans that you’re more likely to get.</h4>
            <h4>We're a credit broker not a lender.</h4>
          </div>
        </div>

        <div class="col-5">
          <div class="banks">
            <span class="barclays"><img src="https://expcdn.co.uk/www/images/icons-homepage-providers/barclays.svg?d13e578de57c521bc4aa27dfb7c0876f" alt="Barclay logo."></span>
            <!-- <span class="hsbc"><img src="https://brandslogos.com/wp-content/uploads/images/large/hsbc-logo-black-and-white.png" alt="hsbc logo"</span> -->
            <span class="icon-homepage-providers virgin"><img src="https://expcdn.co.uk/www/images/icons-homepage-providers/virgin.svg?478bffded488ba49dc2458422b819874" alt="Virgin logo."></span>
            <span class="icon-homepage-providers lloyds"><img src="https://expcdn.co.uk/www/images/icons-homepage-providers/lloyds.svg?8f10b7a8d7fe79208587d31f5a08709f" alt="Lloyds logo."></span>

          </div>
          <div class="banks">
            <span class="barclays"><img src="https://expcdn.co.uk/www/images/icons-homepage-providers/barclays.svg?d13e578de57c521bc4aa27dfb7c0876f" alt="Barclay logo."></span>
            <!-- <span class="hsbc"><img src="https://brandslogos.com/wp-content/uploads/images/large/hsbc-logo-black-and-white.png" alt="hsbc logo"</span> -->
            <span class="icon-homepage-providers virgin"><img src="https://expcdn.co.uk/www/images/icons-homepage-providers/virgin.svg?478bffded488ba49dc2458422b819874" alt="Virgin logo."></span>
            <span class="icon-homepage-providers lloyds"><img src="https://expcdn.co.uk/www/images/icons-homepage-providers/lloyds.svg?8f10b7a8d7fe79208587d31f5a08709f" alt="Lloyds logo."></span>
          </div>
        </div>
      </div>
    </div>
</section>

<!-- Table -->
<section class="table-section">
  <div class="container">
    <h2>Nobody comes closer to what we offer</h2>
    <div class="responsive-table compare">
      <table class="table">
      <thead>
        <tr>
          <th scope="col" class="column1"></th>
          <th scope="colgroup" class="us">Hyperion</th>
          <th scope="col" class="other-plat">Other platforms</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>
            <h5>Monthly credit score monitoring</h5>
            <p>See your data from 4 Credit Reference Agencies, not just one.</p></td>
          <td>Free for everyone</td>
          <td>up to £50</td>
        </tr>

        <tr>
          <td>
            <h5>Compare What's Held About You</h5>
            <p>Simple line-by-line comparison lets you check whether the information held about you by Equifax, Experian and TransUnion matches up, in one place.</p></td>
          <td>Included in the £5 per month subscription</td>
          <td>up to £20</td>
        </tr>

        <tr>
          <td>
            <h5>Check What's Being Reported</h5>
            <p>Check that all reported information is correct including whether or not you have made payments, your personal details and whether the agreements you have are correctly reflected.</p></td>
          <td>Included in subscription</td>
          <td>up to £20</td>
        </tr>

        <tr>
          <td>
            <h5>Monitor your use of credit</h5>
            <p>See how your total borrowings on mortgages, personal loans, credit cards and other accounts have changed over the last 6 years.</p></td>
          <td>Included in subscription</td>
          <td>up to £20</td>

          <tr>
            <td>
              <h5>Personalise Your Credit Report</h5>
              <p>To help you recognise your accounts, to associate them to a more personal purchase such as a car or investment in home improvements.</p></td>
            <td>Included in subscription</td>
            <td>up to £20</td>
        </tr>
      </tbody>
    </table>
  </div>
  </div>
</section>

<!-- Call-to-action -->
<section>
  <div class="container">
    <div class="row">
      <div class="col-10 cta">
        <h3>It never hurts to check, right?</h3>
        <p>See your score at a touch or a glance on our free app. Checking doesn’t affect your score.</p>
        <a href="#"class="btn btn-outline-success cta-button">Sign up free</a>
      </div>
      </div>
    </div>
  </div>
</section>
</body>

{% endblock %}

HyperionApp/templates/login.html
{% extends 'base1.html' %}

{% block content %}

  <!-- Login table -->
  <form action="" method="POST">

    {% csrf_token %}
    <section class="login">
      <div class="container">
        <div class="row">
          <div class="col-12 col-md-8 col-lg-4 login-section">
            <h3 class="title">Log in</h3>

            {% if errors %}
            <div class="alert alert-danger validationErr" role="alert">
              {% for error in errors %}
                {{ error }}
              {% endfor %}
            </div>
            {% endif %}

            <form action="">
              <div class="email-input outline-effect">
                <div class="mb-3">
                  <label for="exampleFormControlInput1" class="form-label">Email address</label>
                  <input type="email" class="form-control" id="exampleFormControlInput1" name="email">
                  <a href="#">Forgotten your username?</a>
                </div>

                <div class="password-input outline-effect">
                  <div class="mb-3">
                    <label for="exampleFormControlInput1" class="form-label">Password</label>
                    <input type="text" class="form-control" id="exampleFormControlInput1" name="password">
                    <a href="#">Forgotten your password?</a>
                  </div>
                </div>
              </form>

              <div class="button-section">
                <button type="submit" class="btn btn-primary login-button">
                  Log in
                  <i class="fas fa-arrow-right"></i>
                </button>
              </div>

              <div class="sign-up">
                <p>Not a member? <a href="#">Sign up free!</a></p>
              </div>
            </div>
          </div>
        </div>
    </section>
  </form>

{% endblock %}

HyperionApp/templates/signup.html
{% extends 'base1.html' %}

{% block content %}

<!-- Sign up form -->
<section class="signup-section">
  <div class="container">
    <div class="row">
      <div class="col-12 col-md-8 col-lg-4 login-section">

        <h3 class="title">Your details</h3>

        <form action="" method="POST">

          {% csrf_token %}

          <div class="signup-input">
            <label class="title">Title</label>
            <select class="form-select form-control outline-effect" aria-label="Default select example" name="title">
              <option>Select...</option>
              <option value="1">Mr</option>
              <option value="2">Mrs</option>
              <option value="3">Miss</option>
              <option value="3">Ms</option>
            </select>

              {% if 'title' in form.errors %}
              <div class="error_message">{{ form.title.errors }}</div>
              {% endif %}

          </div>

          <div class="signup-input outline-effect">
            <label class="first-name">First name</label>
            <input type="text" class="form-control" id="exampleFormControlInput1" name="first_name">

            {% if 'first_name' in form.errors %}
            <div class="error_message">{{ form.first_name.errors }}</div>
            {% endif %}
          </div>

          <div class="signup-input outline-effect">
            <label for="exampleFormControlInput1" class="form-label">Last name(s)</label>
            <input type="text" class="form-control {% if 'last_name' in form.errors %} redborder {% endif %}" id="exampleFormControlInput1" name="last_name">

            {% if 'last_name' in form.errors %}
            <div class="error_message">{{ form.last_name.errors }}</div>
            {% endif %}
          </div>

          <div class="signup-input outline-effect">
            <label for="exampleFormControlInput1" class="form-label">Date of birth</label>
            <div class="dob">
              <input type="text" class="form-control" id="exampleFormControlInput1" placeholder="DD" name="dob_day">
              <input type="text" class="form-control" id="exampleFormControlInput1" placeholder="MM" name="dob_month">
              <input type="text" class="form-control" id="exampleFormControlInput1" placeholder="YYYY" name="dob_year">
            </div>

            {% if 'dob_day' in form.errors or 'dob_month' in form.errors or 'dob_year' in form.errors %}
            <div class="error_message">Date of birth is not valid.</div>
            {% endif %}
          </div>

          <div class="signup-input outline-effect">
            <label for="exampleFormControlInput1" class="form-label">Email address (this will be your username)</label>
            <input type="email" class="form-control" id="exampleFormControlInput1" name="email">

            {% if 'email' in form.errors %}
            <div class="error_message">{{ form.email.errors }}</div>
            {% endif %}
          </div>

          <div class="signup-input outline-effect confirm-email">
            <label for="exampleFormControlInput1" class="form-label">Password</label>
            <input type="password" class="form-control" id="exampleFormControlInput1" name="password">

            {% if 'password' in form.errors %}
            <div class="error_message">{{ form.password.errors }}</div>
            {% endif %}
          </div>

          <div class="signup-input outline-effect">
            <label for="exampleFormControlInput1" class="form-label">Confirm password</label>
            <input type="password" class="form-control" id="exampleFormControlInput1" name="confirm_password">

            {% if 'confirm_password' in form.errors %}
            <div class="error_message">{{ form.confirm_password.errors }}</div>
            {% endif %}
          </div>

          <div class="button-section outline-effect">
            <button type="submit" class="btn btn-primary login-button">
              Sign up
              <i class="fas fa-arrow-right"></i>
            </button>

          <p>By continuing to sign up, you agree to Hyperion's <a href="#">Terms & Conditions</a> and <a href="#">Privacy Policy</a>.
          </div>
          </form>
      </div>
    </div>
  </div>
</section>

{% endblock %}